### ISSUE TITLE
Re-brand the wallet

### ISSUE THREAD

**Issue by wisp3r** [wispproject/wallet#2]
* Change all instances of XSPEC and Spectrecoin to WISP and Wisp respectively.
 * Remove any references to mandatory donations.
 * Add to the copyright notices.
 * Change logo / colours / fonts as appropriate

**Comment by bitcoinx2** [comment]
I offer a bounty of 100 XSPEC for this.

**Comment by bitcoinx2** [comment]
Mostly done (see the `rebrand` branch), only need to replace some graphics and possibly some general design changes to make it visually different from Spectrecoin.
